version: "3.2"
services:
  php:
    build:
      context: "./docker/php/"
    networks:
      - backend
    volumes:
      - .:/var/www/
    environment:
      DB_HOST: postgres
      DEV_SERVER_NAME: topanswers.local
  apache:
    build:
      context: "./docker/apache/"
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/
  postgres:
    build:
      context: ./
      dockerfile: ./docker/postgres/Dockerfile
    restart: always
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
networks:
  frontend:
  backend:
