version: "3.2"
services:
  php:
    build:
      context: "./docker/php/"
    networks:
      - backend
    volumes:
      - .:/var/www/
  apache:
    build:
      context: "./docker/apache/"
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - .:/var/www/
  postgres:
    image: postgres
    restart: always
    networks:
      - backend
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
networks:
  frontend:
  backend:
